package org.jaudiotagger.kt.tag.asf

import org.jaudiotagger.kt.tag.FieldKey

/**
 * ASF content descriptor names for common fields.
 * Generated from AsfFieldKey/AsfTag in the Java sources; do not edit.
 */
internal val asfFieldNames: Map<FieldKey, String> = mapOf(
    FieldKey.ACOUSTID_FINGERPRINT to "Acoustid/Fingerprint",
    FieldKey.ACOUSTID_ID to "Acoustid/Id",
    FieldKey.ALBUM to "WM/AlbumTitle",
    FieldKey.ALBUM_ARTIST to "WM/AlbumArtist",
    FieldKey.ALBUM_ARTIST_SORT to "WM/AlbumArtistSortOrder",
    FieldKey.ALBUM_ARTISTS to "ALBUM_ARTISTS",
    FieldKey.ALBUM_ARTISTS_SORT to "ALBUM_ARTISTS_SORT",
    FieldKey.ALBUM_COMPOSER to "ALBUM_COMPOSER",
    FieldKey.ALBUM_COMPOSER_SORT to "ALBUM_COMPOSER_SORT",
    FieldKey.ALBUM_SORT to "WM/AlbumSortOrder",
    FieldKey.ALBUM_YEAR to "ALBUM_YEAR",
    FieldKey.AMAZON_ID to "ASIN",
    FieldKey.ARRANGER to "WM/Arranger",
    FieldKey.ARRANGER_SORT to "ARRANGER_SORT",
    FieldKey.ARTIST to "AUTHOR",
    FieldKey.ARTISTS to "WM/ARTISTS",
    FieldKey.ARTISTS_SORT to "WM/ARTISTS_SORT",
    FieldKey.ARTIST_SORT to "WM/ArtistSortOrder",
    FieldKey.AUDIO_ENGINEER to "AUDIO_ENGINEER",
    FieldKey.AUDIO_ENGINEER_SORT to "AUDIO_ENGINEER_SORT",
    FieldKey.BALANCE_ENGINEER to "BALANCE_ENGINEER",
    FieldKey.BALANCE_ENGINEER_SORT to "BALANCE_ENGINEER_SORT",
    FieldKey.BARCODE to "WM/Barcode",
    FieldKey.BPM to "WM/BeatsPerMinute",
    FieldKey.CATALOG_NO to "WM/CatalogNo",
    FieldKey.CHOIR to "CHOIR",
    FieldKey.CHOIR_SORT to "CHOIR_SORT",
    FieldKey.CLASSICAL_CATALOG to "CLASSICAL_CATALOG",
    FieldKey.CLASSICAL_NICKNAME to "CLASSICAL_NICKNAME",
    FieldKey.COMMENT to "DESCRIPTION",
    FieldKey.COMPOSER to "WM/Composer",
    FieldKey.COMPOSER_SORT to "WM/ComposerSortOrder",
    FieldKey.CONDUCTOR to "WM/Conductor",
    FieldKey.CONDUCTOR_SORT to "CONDUCTOR_SORT",
    FieldKey.COPYRIGHT to "COPYRIGHT",
    FieldKey.COUNTRY to "WM/Country",
    FieldKey.COVER_ART to "WM/Picture",
    FieldKey.CREDITS to "CREDITS",
    FieldKey.CUSTOM1 to "CUSTOM1",
    FieldKey.CUSTOM2 to "CUSTOM2",
    FieldKey.CUSTOM3 to "CUSTOM3",
    FieldKey.CUSTOM4 to "CUSTOM4",
    FieldKey.CUSTOM5 to "CUSTOM5",
    FieldKey.DISC_NO to "WM/PartOfSet",
    FieldKey.DISC_SUBTITLE to "WM/SetSubTitle",
    FieldKey.DISC_TOTAL to "WM/DiscTotal",
    FieldKey.DJMIXER to "WM/DJMixer",
    FieldKey.DJMIXER_SORT to "DJMIXER_SORT",
    FieldKey.MOOD_ELECTRONIC to "MOOD_ELECTRONIC",
    FieldKey.ENCODER to "WM/ToolName",
    FieldKey.ENGINEER to "WM/Engineer",
    FieldKey.ENGINEER_SORT to "ENGINEER_SORT",
    FieldKey.ENSEMBLE to "ENSEMBLE",
    FieldKey.ENSEMBLE_SORT to "ENSEMBLE_SORT",
    FieldKey.FBPM to "FBPM",
    FieldKey.GENRE to "WM/Genre",
    FieldKey.GROUP to "GROUP",
    FieldKey.GROUPING to "WM/ContentGroupDescription",
    FieldKey.INSTRUMENT to "INSTRUMENT",
    FieldKey.INVOLVEDPEOPLE to "WM/InvolvedPerson",
    FieldKey.IPI to "IPI",
    FieldKey.ISRC to "WM/ISRC",
    FieldKey.ISWC to "ISWC",
    FieldKey.IS_CLASSICAL to "IS_CLASSICAL",
    FieldKey.IS_COMPILATION to "WM/IsCompilation",
    FieldKey.IS_GREATEST_HITS to "IS_GREATEST_HITS",
    FieldKey.IS_HD to "IS_HD",
    FieldKey.IS_LIVE to "LIVE",
    FieldKey.IS_SOUNDTRACK to "IS_SOUNDTRACK",
    FieldKey.JAIKOZ_ID to "JAIKOZ_ID",
    FieldKey.KEY to "WM/InitialKey",
    FieldKey.LANGUAGE to "WM/Language",
    FieldKey.LYRICIST to "WM/Writer",
    FieldKey.LYRICIST_SORT to "LYRICIST_SORT",
    FieldKey.LYRICS to "WM/Lyrics",
    FieldKey.MASTERING to "MASTERING",
    FieldKey.MASTERING_SORT to "MASTERING_SORT",
    FieldKey.MEDIA to "WM/Media",
    FieldKey.MIXER to "WM/Mixer",
    FieldKey.MIXER_SORT to "MIXER_SORT",
    FieldKey.MOOD to "WM/Mood",
    FieldKey.MOOD_ACOUSTIC to "MOOD_ACOUSTIC",
    FieldKey.MOOD_AGGRESSIVE to "MOOD_AGGRESSIVE",
    FieldKey.MOOD_AROUSAL to "MOOD_AROUSAL",
    FieldKey.MOOD_DANCEABILITY to "MOOD_DANCEABILITY",
    FieldKey.MOOD_HAPPY to "MOOD_HAPPY",
    FieldKey.MOOD_INSTRUMENTAL to "MOOD_INSTRUMENTAL",
    FieldKey.MOOD_PARTY to "MOOD_PARTY",
    FieldKey.MOOD_RELAXED to "MOOD_RELAXED",
    FieldKey.MOOD_SAD to "MOOD_SAD",
    FieldKey.MOOD_VALENCE to "MOOD_VALENCE",
    FieldKey.MOVEMENT to "MOVEMENT",
    FieldKey.MOVEMENT_NO to "MOVEMENT_NO",
    FieldKey.MOVEMENT_TOTAL to "MOVEMENT_TOTAL",
    FieldKey.MUSICBRAINZ_ARTISTID to "MusicBrainz/Artist Id",
    FieldKey.MUSICBRAINZ_DISC_ID to "MusicBrainz/Disc Id",
    FieldKey.MUSICBRAINZ_ORIGINAL_RELEASE_ID to "MusicBrainz/Original Album Id",
    FieldKey.MUSICBRAINZ_RELEASEARTISTID to "MusicBrainz/Album Artist Id",
    FieldKey.MUSICBRAINZ_RELEASEID to "MusicBrainz/Album Id",
    FieldKey.MUSICBRAINZ_RELEASE_COUNTRY to "MusicBrainz/Album Release Country",
    FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID to "MusicBrainz/Release Group Id",
    FieldKey.MUSICBRAINZ_RELEASE_STATUS to "MusicBrainz/Album Status",
    FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID to "MusicBrainz/Release Track Id",
    FieldKey.MUSICBRAINZ_RELEASE_TYPE to "MusicBrainz/Album Type",
    FieldKey.MUSICBRAINZ_TRACK_ID to "MusicBrainz/Track Id",
    FieldKey.MUSICBRAINZ_WORK to "MUSICBRAINZ_WORK",
    FieldKey.MUSICBRAINZ_WORK_ID to "MusicBrainz/Work Id",
    FieldKey.MUSICBRAINZ_RECORDING_WORK to "MUSICBRAINZ_RECORDING_WORK",
    FieldKey.MUSICBRAINZ_RECORDING_WORK_ID to "MUSICBRAINZ_RECORDING_WORK_ID",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1 to "MUSICBRAINZ_WORK_PART_LEVEL1",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID to "MUSICBRAINZ_WORK_PART_LEVEL1_ID",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_TYPE to "MUSICBRAINZ_WORK_PART_LEVEL1_TYPE",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2 to "MUSICBRAINZ_WORK_PART_LEVEL2",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID to "MUSICBRAINZ_WORK_PART_LEVEL2_ID",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_TYPE to "MUSICBRAINZ_WORK_PART_LEVEL2_TYPE",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3 to "MUSICBRAINZ_WORK_PART_LEVEL3",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID to "MUSICBRAINZ_WORK_PART_LEVEL3_ID",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_TYPE to "MUSICBRAINZ_WORK_PART_LEVEL3_TYPE",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4 to "MUSICBRAINZ_WORK_PART_LEVEL4",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID to "MUSICBRAINZ_WORK_PART_LEVEL4_ID",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_TYPE to "MUSICBRAINZ_WORK_PART_LEVEL4_TYPE",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5 to "MUSICBRAINZ_WORK_PART_LEVEL5",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID to "MUSICBRAINZ_WORK_PART_LEVEL5_ID",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_TYPE to "MUSICBRAINZ_WORK_PART_LEVEL5_TYPE",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6 to "MUSICBRAINZ_WORK_PART_LEVEL6",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID to "MUSICBRAINZ_WORK_PART_LEVEL6_ID",
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_TYPE to "MUSICBRAINZ_WORK_PART_LEVEL6_TYPE",
    FieldKey.MUSICIP_ID to "MusicIP/PUID",
    FieldKey.OCCASION to "Occasion",
    FieldKey.OPUS to "OPUS",
    FieldKey.ORCHESTRA to "ORCHESTRA",
    FieldKey.ORCHESTRA_SORT to "ORCHESTRA_SORT",
    FieldKey.ORIGINAL_ALBUM to "WM/OriginalAlbumTitle",
    FieldKey.ORIGINAL_ARTIST to "WM/OriginalArtist",
    FieldKey.ORIGINAL_LYRICIST to "WM/OriginalLyricist",
    FieldKey.ORIGINAL_YEAR to "WM/OriginalReleaseYear",
    FieldKey.ORIGINALRELEASEDATE to "ORIGINALRELEASEDATE",
    FieldKey.OVERALL_WORK to "OVERALL_WORK",
    FieldKey.PART to "PART",
    FieldKey.PART_NUMBER to "PARTNUMBER",
    FieldKey.PART_TYPE to "PART_TYPE",
    FieldKey.PERFORMER to "PERFORMER",
    FieldKey.PERFORMER_NAME to "PERFORMER_NAME",
    FieldKey.PERFORMER_NAME_SORT to "PERFORMER_NAME_SORT",
    FieldKey.PERIOD to "PERIOD",
    FieldKey.PRODUCER to "WM/Producer",
    FieldKey.PRODUCER_SORT to "PRODUCER_SORT",
    FieldKey.QUALITY to "Quality",
    FieldKey.RANKING to "RANKING",
    FieldKey.RATING to "WM/SharedUserRating",
    FieldKey.RECORD_LABEL to "WM/Publisher",
    FieldKey.RECORDING_ENGINEER to "RECORDING_ENGINEER",
    FieldKey.RECORDING_ENGINEER_SORT to "RECORDING_ENGINEER_SORT",
    FieldKey.RECORDINGDATE to "RECORDINGDATE",
    FieldKey.RECORDINGSTARTDATE to "RECORDINGSTARTDATE",
    FieldKey.RECORDINGENDDATE to "RECORDINGENDDATE",
    FieldKey.RECORDINGLOCATION to "RECORDINGLOCATION",
    FieldKey.REMIXER to "WM/ModifiedBy",
    FieldKey.ROONALBUMTAG to "ROONALBUMTAG",
    FieldKey.ROONTRACKTAG to "ROONTRACKTAG",
    FieldKey.SCRIPT to "WM/Script",
    FieldKey.SECTION to "SECTION",
    FieldKey.SINGLE_DISC_TRACK_NO to "SINGLE_DISC_TRACK_NO",
    FieldKey.SONGKONG_ID to "SONGKONG_ID",
    FieldKey.SOUND_ENGINEER to "SOUND_ENGINEER",
    FieldKey.SOUND_ENGINEER_SORT to "SOUND_ENGINEER_SORT",
    FieldKey.SUBTITLE to "WM/SubTitle",
    FieldKey.TAGS to "WM/Tags",
    FieldKey.TEMPO to "Tempo",
    FieldKey.TIMBRE to "TIMBRE_BRIGHTNESS",
    FieldKey.TITLE to "TITLE",
    FieldKey.TITLE_MOVEMENT to "TITLE_MOVEMENT",
    FieldKey.TITLE_SORT to "WM/TitleSortOrder",
    FieldKey.TONALITY to "TONALITY",
    FieldKey.TRACK to "WM/TrackNumber",
    FieldKey.TRACK_TOTAL to "WM/TrackTotal",
    FieldKey.URL_BANDCAMP_ARTIST_SITE to "WM/BandcampArtistUrl",
    FieldKey.URL_BANDCAMP_RELEASE_SITE to "WM/BandcampReleaseUrl",
    FieldKey.URL_DISCOGS_ARTIST_SITE to "WM/DiscogsArtistUrl",
    FieldKey.URL_DISCOGS_RELEASE_SITE to "WM/DiscogsReleaseUrl",
    FieldKey.URL_LYRICS_SITE to "WM/LyricsUrl",
    FieldKey.URL_OFFICIAL_ARTIST_SITE to "WM/AuthorURL",
    FieldKey.URL_OFFICIAL_RELEASE_SITE to "WM/OfficialReleaseUrl",
    FieldKey.URL_WIKIPEDIA_ARTIST_SITE to "WM/WikipediaArtistUrl",
    FieldKey.URL_WIKIPEDIA_RELEASE_SITE to "WM/WikipediaReleaseUrl",
    FieldKey.VERSION to "VERSION",
    FieldKey.WORK to "WORK",
    FieldKey.WORK_TYPE to "WORK_TYPE",
    FieldKey.YEAR to "WM/Year",
)
