package org.jaudiotagger.kt.tag.id3

import org.jaudiotagger.kt.tag.FieldKey

/**
 * Where a [FieldKey] lives in an ID3v2 tag: the frame id plus, for container
 * frames (TXXX/WXXX/COMM/IPLS...), the sub-key (description) inside it.
 *
 * Generated from ID3v2xFieldKey/ID3v2xFrames in the Java sources; do not edit.
 */
class Id3FrameKey(val frameId: String, val subId: String? = null, val isBinary: Boolean = false)

internal val id3v24FrameKeys: Map<FieldKey, Id3FrameKey> = mapOf(
    FieldKey.ACOUSTID_FINGERPRINT to Id3FrameKey("TXXX", "Acoustid Fingerprint"),
    FieldKey.ACOUSTID_ID to Id3FrameKey("TXXX", "Acoustid Id"),
    FieldKey.ALBUM to Id3FrameKey("TALB"),
    FieldKey.ALBUM_ARTIST to Id3FrameKey("TPE2"),
    FieldKey.ALBUM_ARTIST_SORT to Id3FrameKey("TSO2"),
    FieldKey.ALBUM_ARTISTS to Id3FrameKey("TXXX", "ALBUM_ARTISTS"),
    FieldKey.ALBUM_ARTISTS_SORT to Id3FrameKey("TXXX", "ALBUM_ARTISTS_SORT"),
    FieldKey.ALBUM_COMPOSER to Id3FrameKey("TXXX", "ALBUM_COMPOSER"),
    FieldKey.ALBUM_COMPOSER_SORT to Id3FrameKey("TXXX", "ALBUM_COMPOSER_SORT"),
    FieldKey.ALBUM_SORT to Id3FrameKey("TSOA"),
    FieldKey.ALBUM_YEAR to Id3FrameKey("TXXX", "ALBUM_YEAR"),
    FieldKey.AMAZON_ID to Id3FrameKey("TXXX", "ASIN"),
    FieldKey.ARRANGER to Id3FrameKey("TXXX", "ARRANGER"),
    FieldKey.ARRANGER_SORT to Id3FrameKey("TXXX", "ARRANGER_SORT"),
    FieldKey.ARTIST to Id3FrameKey("TPE1"),
    FieldKey.ARTISTS to Id3FrameKey("TXXX", "ARTISTS"),
    FieldKey.ARTISTS_SORT to Id3FrameKey("TXXX", "ARTISTS_SORT"),
    FieldKey.ARTIST_SORT to Id3FrameKey("TSOP"),
    FieldKey.AUDIO_ENGINEER to Id3FrameKey("TXXX", "AUDIO_ENGINEER"),
    FieldKey.AUDIO_ENGINEER_SORT to Id3FrameKey("TXXX", "AUDIO_ENGINEER_SORT"),
    FieldKey.BALANCE_ENGINEER to Id3FrameKey("TXXX", "BALANCE_ENGINEER"),
    FieldKey.BALANCE_ENGINEER_SORT to Id3FrameKey("TXXX", "BALANCE_ENGINEER_SORT"),
    FieldKey.BARCODE to Id3FrameKey("TXXX", "BARCODE"),
    FieldKey.BPM to Id3FrameKey("TBPM"),
    FieldKey.CATALOG_NO to Id3FrameKey("TXXX", "CATALOGNUMBER"),
    FieldKey.CHOIR to Id3FrameKey("TXXX", "CHOIR"),
    FieldKey.CHOIR_SORT to Id3FrameKey("TXXX", "CHOIR_SORT"),
    FieldKey.CLASSICAL_CATALOG to Id3FrameKey("TXXX", "CLASSICAL_CATALOG"),
    FieldKey.CLASSICAL_NICKNAME to Id3FrameKey("TXXX", "CLASSICAL_NICKNAME"),
    FieldKey.COMMENT to Id3FrameKey("COMM"),
    FieldKey.COMPOSER to Id3FrameKey("TCOM"),
    FieldKey.COMPOSER_SORT to Id3FrameKey("TSOC"),
    FieldKey.CONDUCTOR to Id3FrameKey("TPE3"),
    FieldKey.CONDUCTOR_SORT to Id3FrameKey("TXXX", "CONDUCTOR_SORT"),
    FieldKey.COPYRIGHT to Id3FrameKey("TCOP"),
    FieldKey.COUNTRY to Id3FrameKey("TXXX", "Country"),
    FieldKey.COVER_ART to Id3FrameKey("APIC", isBinary = true),
    FieldKey.CREDITS to Id3FrameKey("TXXX", "CREDITS"),
    FieldKey.CUSTOM1 to Id3FrameKey("COMM", "Songs-DB_Custom1"),
    FieldKey.CUSTOM2 to Id3FrameKey("COMM", "Songs-DB_Custom2"),
    FieldKey.CUSTOM3 to Id3FrameKey("COMM", "Songs-DB_Custom3"),
    FieldKey.CUSTOM4 to Id3FrameKey("COMM", "Songs-DB_Custom4"),
    FieldKey.CUSTOM5 to Id3FrameKey("COMM", "Songs-DB_Custom5"),
    FieldKey.DISC_NO to Id3FrameKey("TPOS"),
    FieldKey.DISC_SUBTITLE to Id3FrameKey("TSST"),
    FieldKey.DISC_TOTAL to Id3FrameKey("TPOS"),
    FieldKey.DJMIXER to Id3FrameKey("TXXX", "DJMIXER"),
    FieldKey.DJMIXER_SORT to Id3FrameKey("TXXX", "DJMIXER_SORT"),
    FieldKey.MOOD_ELECTRONIC to Id3FrameKey("TXXX", "MOOD_ELECTRONIC"),
    FieldKey.ENCODER to Id3FrameKey("TENC"),
    FieldKey.ENGINEER to Id3FrameKey("TXXX", "ENGINEER"),
    FieldKey.ENGINEER_SORT to Id3FrameKey("TXXX", "ENGINEER_SORT"),
    FieldKey.ENSEMBLE to Id3FrameKey("TXXX", "ENSEMBLE"),
    FieldKey.ENSEMBLE_SORT to Id3FrameKey("TXXX", "ENSEMBLE_SORT"),
    FieldKey.FBPM to Id3FrameKey("TXXX", "FBPM"),
    FieldKey.GENRE to Id3FrameKey("TCON"),
    FieldKey.GROUP to Id3FrameKey("TXXX", "GROUP"),
    FieldKey.GROUPING to Id3FrameKey("TIT1"),
    FieldKey.INSTRUMENT to Id3FrameKey("TXXX", "INSTRUMENT"),
    FieldKey.INVOLVEDPEOPLE to Id3FrameKey("TIPL"),
    FieldKey.IPI to Id3FrameKey("TXXX", "IPI"),
    FieldKey.ISRC to Id3FrameKey("TSRC"),
    FieldKey.ISWC to Id3FrameKey("TXXX", "ISWC"),
    FieldKey.IS_CLASSICAL to Id3FrameKey("TXXX", "IS_CLASSICAL"),
    FieldKey.IS_COMPILATION to Id3FrameKey("TCMP"),
    FieldKey.IS_SOUNDTRACK to Id3FrameKey("TXXX", "IS_SOUNDTRACK"),
    FieldKey.IS_GREATEST_HITS to Id3FrameKey("TXXX", "IS_GREATEST_HITS"),
    FieldKey.IS_HD to Id3FrameKey("TXXX", "IS_HD"),
    FieldKey.IS_LIVE to Id3FrameKey("TXXX", "LIVE"),
    FieldKey.ITUNES_GROUPING to Id3FrameKey("GRP1"),
    FieldKey.JAIKOZ_ID to Id3FrameKey("TXXX", "JAIKOZ_ID"),
    FieldKey.KEY to Id3FrameKey("TKEY"),
    FieldKey.LANGUAGE to Id3FrameKey("TLAN"),
    FieldKey.LYRICIST to Id3FrameKey("TEXT"),
    FieldKey.LYRICIST_SORT to Id3FrameKey("TXXX", "LYRICIST_SORT"),
    FieldKey.LYRICS to Id3FrameKey("USLT"),
    FieldKey.MASTERING to Id3FrameKey("TXXX", "MASTERING"),
    FieldKey.MASTERING_SORT to Id3FrameKey("TXXX", "MASTERING_SORT"),
    FieldKey.MEDIA to Id3FrameKey("TMED"),
    FieldKey.MIXER to Id3FrameKey("TXXX", "MIXER"),
    FieldKey.MIXER_SORT to Id3FrameKey("TXXX", "MIXER_SORT"),
    FieldKey.MOOD to Id3FrameKey("TMOO"),
    FieldKey.MOOD_ACOUSTIC to Id3FrameKey("TXXX", "MOOD_ACOUSTIC"),
    FieldKey.MOOD_AGGRESSIVE to Id3FrameKey("TXXX", "MOOD_AGGRESSIVE"),
    FieldKey.MOOD_AROUSAL to Id3FrameKey("TXXX", "MOOD_AROUSAL"),
    FieldKey.MOOD_DANCEABILITY to Id3FrameKey("TXXX", "MOOD_DANCEABILITY"),
    FieldKey.MOOD_HAPPY to Id3FrameKey("TXXX", "MOOD_HAPPY"),
    FieldKey.MOOD_INSTRUMENTAL to Id3FrameKey("TXXX", "MOOD_INSTRUMENTAL"),
    FieldKey.MOOD_PARTY to Id3FrameKey("TXXX", "MOOD_PARTY"),
    FieldKey.MOOD_RELAXED to Id3FrameKey("TXXX", "MOOD_RELAXED"),
    FieldKey.MOOD_SAD to Id3FrameKey("TXXX", "MOOD_SAD"),
    FieldKey.MOOD_VALENCE to Id3FrameKey("TXXX", "MOOD_VALENCE"),
    FieldKey.MOVEMENT to Id3FrameKey("MVNM"),
    FieldKey.MOVEMENT_NO to Id3FrameKey("MVIN"),
    FieldKey.MOVEMENT_TOTAL to Id3FrameKey("MVIN"),
    FieldKey.MUSICBRAINZ_ARTISTID to Id3FrameKey("TXXX", "MusicBrainz Artist Id"),
    FieldKey.MUSICBRAINZ_DISC_ID to Id3FrameKey("TXXX", "MusicBrainz Disc Id"),
    FieldKey.MUSICBRAINZ_ORIGINAL_RELEASE_ID to Id3FrameKey(
        "TXXX",
        "MusicBrainz Original Album Id"
    ),
    FieldKey.MUSICBRAINZ_RELEASEARTISTID to Id3FrameKey("TXXX", "MusicBrainz Album Artist Id"),
    FieldKey.MUSICBRAINZ_RELEASEID to Id3FrameKey("TXXX", "MusicBrainz Album Id"),
    FieldKey.MUSICBRAINZ_RELEASE_COUNTRY to Id3FrameKey(
        "TXXX",
        "MusicBrainz Album Release Country"
    ),
    FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID to Id3FrameKey("TXXX", "MusicBrainz Release Group Id"),
    FieldKey.MUSICBRAINZ_RELEASE_STATUS to Id3FrameKey("TXXX", "MusicBrainz Album Status"),
    FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID to Id3FrameKey("TXXX", "MusicBrainz Release Track Id"),
    FieldKey.MUSICBRAINZ_RELEASE_TYPE to Id3FrameKey("TXXX", "MusicBrainz Album Type"),
    FieldKey.MUSICBRAINZ_TRACK_ID to Id3FrameKey("UFID", "http://musicbrainz.org"),
    FieldKey.MUSICBRAINZ_WORK to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK"),
    FieldKey.MUSICBRAINZ_WORK_ID to Id3FrameKey("TXXX", "MusicBrainz Work Id"),
    FieldKey.MUSICBRAINZ_RECORDING_WORK to Id3FrameKey("TXXX", "MUSICBRAINZ_RECORDING_WORK"),
    FieldKey.MUSICBRAINZ_RECORDING_WORK_ID to Id3FrameKey("TXXX", "MUSICBRAINZ_RECORDING_WORK_ID"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL1_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL2_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL3_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL4_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL5_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL6_ID"
    ),
    FieldKey.MUSICIP_ID to Id3FrameKey("TXXX", "MusicIP PUID"),
    FieldKey.OCCASION to Id3FrameKey("COMM", "Songs-DB_Occasion"),
    FieldKey.OPUS to Id3FrameKey("TXXX", "OPUS"),
    FieldKey.ORCHESTRA to Id3FrameKey("TXXX", "ORCHESTRA"),
    FieldKey.ORCHESTRA_SORT to Id3FrameKey("TXXX", "ORCHESTRA_SORT"),
    FieldKey.ORIGINAL_ALBUM to Id3FrameKey("TOAL"),
    FieldKey.ORIGINALRELEASEDATE to Id3FrameKey("TXXX", "ORIGINALRELEASEDATE"),
    FieldKey.ORIGINAL_ARTIST to Id3FrameKey("TOPE"),
    FieldKey.ORIGINAL_LYRICIST to Id3FrameKey("TOLY"),
    FieldKey.ORIGINAL_YEAR to Id3FrameKey("TDOR"),
    FieldKey.OVERALL_WORK to Id3FrameKey("TXXX", "OVERALL_WORK"),
    FieldKey.PART to Id3FrameKey("TXXX", "PART"),
    FieldKey.PART_NUMBER to Id3FrameKey("TXXX", "PARTNUMBER"),
    FieldKey.PART_TYPE to Id3FrameKey("TXXX", "PART_TYPE"),
    FieldKey.PERFORMER to Id3FrameKey("TXXX", "PERFORMER"),
    FieldKey.PERFORMER_NAME to Id3FrameKey("TXXX", "PERFORMER_NAME"),
    FieldKey.PERFORMER_NAME_SORT to Id3FrameKey("TXXX", "PERFORMER_NAME_SORT"),
    FieldKey.PERIOD to Id3FrameKey("TXXX", "PERIOD"),
    FieldKey.PRODUCER to Id3FrameKey("TXXX", "PRODUCER"),
    FieldKey.PRODUCER_SORT to Id3FrameKey("TXXX", "PRODUCER_SORT"),
    FieldKey.QUALITY to Id3FrameKey("COMM", "Songs-DB_Preference"),
    FieldKey.RANKING to Id3FrameKey("TXXX", "RANKING"),
    FieldKey.RATING to Id3FrameKey("POPM"),
    FieldKey.RECORDING_ENGINEER to Id3FrameKey("TXXX", "RECORDING_ENGINEER"),
    FieldKey.RECORDING_ENGINEER_SORT to Id3FrameKey("TXXX", "RECORDING_ENGINEER_SORT"),
    FieldKey.RECORD_LABEL to Id3FrameKey("TPUB"),
    FieldKey.RECORDINGDATE to Id3FrameKey("TXXX", "RECORDINGDATE"),
    FieldKey.RECORDINGSTARTDATE to Id3FrameKey("TXXX", "RECORDINGSTARTDATE"),
    FieldKey.RECORDINGENDDATE to Id3FrameKey("TXXX", "RECORDINGENDDATE"),
    FieldKey.RECORDINGLOCATION to Id3FrameKey("TXXX", "RECORDINGLOCATION"),
    FieldKey.REMIXER to Id3FrameKey("TPE4"),
    FieldKey.ROONALBUMTAG to Id3FrameKey("TXXX", "ROONALBUMTAG"),
    FieldKey.ROONTRACKTAG to Id3FrameKey("TXXX", "ROONTRACKTAG"),
    FieldKey.SCRIPT to Id3FrameKey("TXXX", "SCRIPT"),
    FieldKey.SECTION to Id3FrameKey("TXXX", "SECTION"),
    FieldKey.SINGLE_DISC_TRACK_NO to Id3FrameKey("TXXX", "SINGLE_DISC_TRACK_NO"),
    FieldKey.SONGKONG_ID to Id3FrameKey("TXXX", "SONGKONG_ID"),
    FieldKey.SOUND_ENGINEER to Id3FrameKey("TXXX", "SOUND_ENGINEER"),
    FieldKey.SOUND_ENGINEER_SORT to Id3FrameKey("TXXX", "SOUND_ENGINEER_SORT"),
    FieldKey.SUBTITLE to Id3FrameKey("TIT3"),
    FieldKey.TAGS to Id3FrameKey("TXXX", "TAGS"),
    FieldKey.TEMPO to Id3FrameKey("COMM", "Songs-DB_Tempo"),
    FieldKey.TIMBRE to Id3FrameKey("TXXX", "TIMBRE_BRIGHTNESS"),
    FieldKey.TITLE to Id3FrameKey("TIT2"),
    FieldKey.TITLE_MOVEMENT to Id3FrameKey("TXXX", "TITLE_MOVEMENT"),
    FieldKey.TITLE_SORT to Id3FrameKey("TSOT"),
    FieldKey.TONALITY to Id3FrameKey("TXXX", "TONALITY"),
    FieldKey.TRACK to Id3FrameKey("TRCK"),
    FieldKey.TRACK_TOTAL to Id3FrameKey("TRCK"),
    FieldKey.URL_BANDCAMP_ARTIST_SITE to Id3FrameKey("WXXX", "BANDCAMP_ARTIST"),
    FieldKey.URL_BANDCAMP_RELEASE_SITE to Id3FrameKey("WXXX", "BANDCAMP_RELEASE"),
    FieldKey.URL_DISCOGS_ARTIST_SITE to Id3FrameKey("WXXX", "DISCOGS_ARTIST"),
    FieldKey.URL_DISCOGS_RELEASE_SITE to Id3FrameKey("WXXX", "DISCOGS_RELEASE"),
    FieldKey.URL_LYRICS_SITE to Id3FrameKey("WXXX", "LYRICS_SITE"),
    FieldKey.URL_OFFICIAL_ARTIST_SITE to Id3FrameKey("WOAR"),
    FieldKey.URL_OFFICIAL_RELEASE_SITE to Id3FrameKey("WXXX", "OFFICIAL_RELEASE"),
    FieldKey.URL_WIKIPEDIA_ARTIST_SITE to Id3FrameKey("WXXX", "WIKIPEDIA_ARTIST"),
    FieldKey.URL_WIKIPEDIA_RELEASE_SITE to Id3FrameKey("WXXX", "WIKIPEDIA_RELEASE"),
    FieldKey.WORK to Id3FrameKey("TXXX", "WORK"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL1"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL1_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL2"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL2_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL3"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL3_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL4"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL4_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL5"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL5_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL6"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL6_TYPE"
    ),
    FieldKey.VERSION to Id3FrameKey("TXXX", "VERSION"),
    FieldKey.WORK_TYPE to Id3FrameKey("TXXX", "WORK_TYPE"),
    FieldKey.YEAR to Id3FrameKey("TDRC"),
    FieldKey.WORK to Id3FrameKey("TIT1"),
    FieldKey.GROUPING to Id3FrameKey("GRP1"),
    FieldKey.WORK to Id3FrameKey("TXXX", "WORK"),
    FieldKey.GROUPING to Id3FrameKey("TIT1"),
)

internal val id3v23FrameKeys: Map<FieldKey, Id3FrameKey> = mapOf(
    FieldKey.ACOUSTID_FINGERPRINT to Id3FrameKey("TXXX", "Acoustid Fingerprint"),
    FieldKey.ACOUSTID_ID to Id3FrameKey("TXXX", "Acoustid Id"),
    FieldKey.ALBUM to Id3FrameKey("TALB"),
    FieldKey.ALBUM_ARTIST to Id3FrameKey("TPE2"),
    FieldKey.ALBUM_ARTIST_SORT to Id3FrameKey("TSO2"),
    FieldKey.ALBUM_ARTISTS to Id3FrameKey("TXXX", "ALBUM_ARTISTS"),
    FieldKey.ALBUM_ARTISTS_SORT to Id3FrameKey("TXXX", "ALBUM_ARTISTS_SORT"),
    FieldKey.ALBUM_COMPOSER to Id3FrameKey("TXXX", "ALBUM_COMPOSER"),
    FieldKey.ALBUM_COMPOSER_SORT to Id3FrameKey("TXXX", "ALBUM_COMPOSER_SORT"),
    FieldKey.ALBUM_SORT to Id3FrameKey("TSOA"),
    FieldKey.ALBUM_YEAR to Id3FrameKey("TXXX", "ALBUM_YEAR"),
    FieldKey.AMAZON_ID to Id3FrameKey("TXXX", "ASIN"),
    FieldKey.ARRANGER to Id3FrameKey("TXXX", "ARRANGER"),
    FieldKey.ARRANGER_SORT to Id3FrameKey("TXXX", "ARRANGER_SORT"),
    FieldKey.ARTIST to Id3FrameKey("TPE1"),
    FieldKey.ARTISTS to Id3FrameKey("TXXX", "ARTISTS"),
    FieldKey.ARTISTS_SORT to Id3FrameKey("TXXX", "ARTISTS_SORT"),
    FieldKey.ARTIST_SORT to Id3FrameKey("TSOP"),
    FieldKey.AUDIO_ENGINEER to Id3FrameKey("TXXX", "AUDIO_ENGINEER"),
    FieldKey.AUDIO_ENGINEER_SORT to Id3FrameKey("TXXX", "AUDIO_ENGINEER_SORT"),
    FieldKey.BALANCE_ENGINEER to Id3FrameKey("TXXX", "BALANCE_ENGINEER"),
    FieldKey.BALANCE_ENGINEER_SORT to Id3FrameKey("TXXX", "BALANCE_ENGINEER_SORT"),
    FieldKey.BARCODE to Id3FrameKey("TXXX", "BARCODE"),
    FieldKey.BPM to Id3FrameKey("TBPM"),
    FieldKey.CATALOG_NO to Id3FrameKey("TXXX", "CATALOGNUMBER"),
    FieldKey.CHOIR to Id3FrameKey("TXXX", "CHOIR"),
    FieldKey.CHOIR_SORT to Id3FrameKey("TXXX", "CHOIR_SORT"),
    FieldKey.CLASSICAL_CATALOG to Id3FrameKey("TXXX", "CLASSICAL_CATALOG"),
    FieldKey.CLASSICAL_NICKNAME to Id3FrameKey("TXXX", "CLASSICAL_NICKNAME"),
    FieldKey.COMMENT to Id3FrameKey("COMM"),
    FieldKey.COMPOSER to Id3FrameKey("TCOM"),
    FieldKey.COMPOSER_SORT to Id3FrameKey("TSOC"),
    FieldKey.CONDUCTOR to Id3FrameKey("TPE3"),
    FieldKey.CONDUCTOR_SORT to Id3FrameKey("TXXX", "CONDUCTOR_SORT"),
    FieldKey.COPYRIGHT to Id3FrameKey("TCOP"),
    FieldKey.COUNTRY to Id3FrameKey("TXXX", "Country"),
    FieldKey.COVER_ART to Id3FrameKey("APIC", isBinary = true),
    FieldKey.CREDITS to Id3FrameKey("TXXX", "CREDITS"),
    FieldKey.CUSTOM1 to Id3FrameKey("COMM", "Songs-DB_Custom1"),
    FieldKey.CUSTOM2 to Id3FrameKey("COMM", "Songs-DB_Custom2"),
    FieldKey.CUSTOM3 to Id3FrameKey("COMM", "Songs-DB_Custom3"),
    FieldKey.CUSTOM4 to Id3FrameKey("COMM", "Songs-DB_Custom4"),
    FieldKey.CUSTOM5 to Id3FrameKey("COMM", "Songs-DB_Custom5"),
    FieldKey.DISC_NO to Id3FrameKey("TPOS"),
    FieldKey.DISC_SUBTITLE to Id3FrameKey("TSST"),
    FieldKey.DISC_TOTAL to Id3FrameKey("TPOS"),
    FieldKey.DJMIXER to Id3FrameKey("TXXX", "DJMIXER"),
    FieldKey.DJMIXER_SORT to Id3FrameKey("TXXX", "DJMIXER_SORT"),
    FieldKey.MOOD_ELECTRONIC to Id3FrameKey("TXXX", "MOOD_ELECTRONIC"),
    FieldKey.ENCODER to Id3FrameKey("TENC"),
    FieldKey.ENGINEER to Id3FrameKey("TXXX", "ENGINEER"),
    FieldKey.ENGINEER_SORT to Id3FrameKey("TXXX", "ENGINEER_SORT"),
    FieldKey.ENSEMBLE to Id3FrameKey("TXXX", "ENSEMBLE"),
    FieldKey.ENSEMBLE_SORT to Id3FrameKey("TXXX", "ENSEMBLE_SORT"),
    FieldKey.FBPM to Id3FrameKey("TXXX", "FBPM"),
    FieldKey.GENRE to Id3FrameKey("TCON"),
    FieldKey.GROUP to Id3FrameKey("TXXX", "GROUP"),
    FieldKey.GROUPING to Id3FrameKey("TIT1"),
    FieldKey.INSTRUMENT to Id3FrameKey("TXXX", "INSTRUMENT"),
    FieldKey.INVOLVEDPEOPLE to Id3FrameKey("IPLS"),
    FieldKey.IPI to Id3FrameKey("TXXX", "IPI"),
    FieldKey.ISRC to Id3FrameKey("TSRC"),
    FieldKey.ISWC to Id3FrameKey("TXXX", "ISWC"),
    FieldKey.IS_CLASSICAL to Id3FrameKey("TXXX", "IS_CLASSICAL"),
    FieldKey.IS_COMPILATION to Id3FrameKey("TCMP"),
    FieldKey.IS_GREATEST_HITS to Id3FrameKey("TXXX", "IS_GREATEST_HITS"),
    FieldKey.IS_HD to Id3FrameKey("TXXX", "IS_HD"),
    FieldKey.IS_LIVE to Id3FrameKey("TXXX", "LIVE"),
    FieldKey.IS_SOUNDTRACK to Id3FrameKey("TXXX", "IS_SOUNDTRACK"),
    FieldKey.ITUNES_GROUPING to Id3FrameKey("GRP1"),
    FieldKey.JAIKOZ_ID to Id3FrameKey("TXXX", "JAIKOZ_ID"),
    FieldKey.KEY to Id3FrameKey("TKEY"),
    FieldKey.LANGUAGE to Id3FrameKey("TLAN"),
    FieldKey.LYRICIST to Id3FrameKey("TEXT"),
    FieldKey.LYRICIST_SORT to Id3FrameKey("TXXX", "LYRICIST_SORT"),
    FieldKey.LYRICS to Id3FrameKey("USLT"),
    FieldKey.MASTERING to Id3FrameKey("TXXX", "MASTERING"),
    FieldKey.MASTERING_SORT to Id3FrameKey("TXXX", "MASTERING_SORT"),
    FieldKey.MEDIA to Id3FrameKey("TMED"),
    FieldKey.MIXER to Id3FrameKey("TXXX", "MIXER"),
    FieldKey.MIXER_SORT to Id3FrameKey("TXXX", "MIXER_SORT"),
    FieldKey.MOOD to Id3FrameKey("TXXX", "MOOD"),
    FieldKey.MOOD_ACOUSTIC to Id3FrameKey("TXXX", "MOOD_ACOUSTIC"),
    FieldKey.MOOD_AGGRESSIVE to Id3FrameKey("TXXX", "MOOD_AGGRESSIVE"),
    FieldKey.MOOD_AROUSAL to Id3FrameKey("TXXX", "MOOD_AROUSAL"),
    FieldKey.MOOD_DANCEABILITY to Id3FrameKey("TXXX", "MOOD_DANCEABILITY"),
    FieldKey.MOOD_HAPPY to Id3FrameKey("TXXX", "MOOD_HAPPY"),
    FieldKey.MOOD_INSTRUMENTAL to Id3FrameKey("TXXX", "MOOD_INSTRUMENTAL"),
    FieldKey.MOOD_PARTY to Id3FrameKey("TXXX", "MOOD_PARTY"),
    FieldKey.MOOD_RELAXED to Id3FrameKey("TXXX", "MOOD_RELAXED"),
    FieldKey.MOOD_SAD to Id3FrameKey("TXXX", "MOOD_SAD"),
    FieldKey.MOOD_VALENCE to Id3FrameKey("TXXX", "MOOD_VALENCE"),
    FieldKey.MOVEMENT to Id3FrameKey("MVNM"),
    FieldKey.MOVEMENT_NO to Id3FrameKey("MVIN"),
    FieldKey.MOVEMENT_TOTAL to Id3FrameKey("MVIN"),
    FieldKey.MUSICBRAINZ_ARTISTID to Id3FrameKey("TXXX", "MusicBrainz Artist Id"),
    FieldKey.MUSICBRAINZ_DISC_ID to Id3FrameKey("TXXX", "MusicBrainz Disc Id"),
    FieldKey.MUSICBRAINZ_ORIGINAL_RELEASE_ID to Id3FrameKey(
        "TXXX",
        "MusicBrainz Original Album Id"
    ),
    FieldKey.MUSICBRAINZ_RELEASEARTISTID to Id3FrameKey("TXXX", "MusicBrainz Album Artist Id"),
    FieldKey.MUSICBRAINZ_RELEASEID to Id3FrameKey("TXXX", "MusicBrainz Album Id"),
    FieldKey.MUSICBRAINZ_RELEASE_COUNTRY to Id3FrameKey(
        "TXXX",
        "MusicBrainz Album Release Country"
    ),
    FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID to Id3FrameKey("TXXX", "MusicBrainz Release Group Id"),
    FieldKey.MUSICBRAINZ_RELEASE_STATUS to Id3FrameKey("TXXX", "MusicBrainz Album Status"),
    FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID to Id3FrameKey("TXXX", "MusicBrainz Release Track Id"),
    FieldKey.MUSICBRAINZ_RELEASE_TYPE to Id3FrameKey("TXXX", "MusicBrainz Album Type"),
    FieldKey.MUSICBRAINZ_TRACK_ID to Id3FrameKey("UFID", "http://musicbrainz.org"),
    FieldKey.MUSICBRAINZ_WORK to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK"),
    FieldKey.MUSICBRAINZ_WORK_ID to Id3FrameKey("TXXX", "MusicBrainz Work Id"),
    FieldKey.MUSICBRAINZ_RECORDING_WORK_ID to Id3FrameKey("TXXX", "MUSICBRAINZ_RECORDING_WORK_ID"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL1_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL2_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL3_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL4_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL5_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL6_ID"
    ),
    FieldKey.MUSICIP_ID to Id3FrameKey("TXXX", "MusicIP PUID"),
    FieldKey.OCCASION to Id3FrameKey("COMM", "Songs-DB_Occasion"),
    FieldKey.OPUS to Id3FrameKey("TXXX", "OPUS"),
    FieldKey.ORCHESTRA to Id3FrameKey("TXXX", "ORCHESTRA"),
    FieldKey.ORCHESTRA_SORT to Id3FrameKey("TXXX", "ORCHESTRA_SORT"),
    FieldKey.ORIGINAL_ALBUM to Id3FrameKey("TOAL"),
    FieldKey.ORIGINALRELEASEDATE to Id3FrameKey("TXXX", "ORIGINALRELEASEDATE"),
    FieldKey.ORIGINAL_ARTIST to Id3FrameKey("TOPE"),
    FieldKey.ORIGINAL_LYRICIST to Id3FrameKey("TOLY"),
    FieldKey.ORIGINAL_YEAR to Id3FrameKey("TORY"),
    FieldKey.OVERALL_WORK to Id3FrameKey("TXXX", "OVERALL_WORK"),
    FieldKey.PART to Id3FrameKey("TXXX", "PART"),
    FieldKey.PART_NUMBER to Id3FrameKey("TXXX", "PARTNUMBER"),
    FieldKey.PART_TYPE to Id3FrameKey("TXXX", "PART_TYPE"),
    FieldKey.PERFORMER to Id3FrameKey("TXXX", "PERFORMER"),
    FieldKey.PERFORMER_NAME to Id3FrameKey("TXXX", "PERFORMER_NAME"),
    FieldKey.PERFORMER_NAME_SORT to Id3FrameKey("TXXX", "PERFORMER_NAME_SORT"),
    FieldKey.PERIOD to Id3FrameKey("TXXX", "PERIOD"),
    FieldKey.PRODUCER to Id3FrameKey("TXXX", "PRODUCER"),
    FieldKey.PRODUCER_SORT to Id3FrameKey("TXXX", "PRODUCER_SORT"),
    FieldKey.QUALITY to Id3FrameKey("COMM", "Songs-DB_Preference"),
    FieldKey.RANKING to Id3FrameKey("TXXX", "RANKING"),
    FieldKey.RATING to Id3FrameKey("POPM"),
    FieldKey.RECORDING_ENGINEER to Id3FrameKey("TXXX", "RECORDING_ENGINEER"),
    FieldKey.RECORDING_ENGINEER_SORT to Id3FrameKey("TXXX", "RECORDING_ENGINEER_SORT"),
    FieldKey.RECORD_LABEL to Id3FrameKey("TPUB"),
    FieldKey.RECORDINGDATE to Id3FrameKey("TXXX", "RECORDINGDATE"),
    FieldKey.RECORDINGSTARTDATE to Id3FrameKey("TXXX", "RECORDINGSTARTDATE"),
    FieldKey.RECORDINGENDDATE to Id3FrameKey("TXXX", "RECORDINGENDDATE"),
    FieldKey.RECORDINGLOCATION to Id3FrameKey("TXXX", "RECORDINGLOCATION"),
    FieldKey.REMIXER to Id3FrameKey("TPE4"),
    FieldKey.ROONALBUMTAG to Id3FrameKey("TXXX", "ROONALBUMTAG"),
    FieldKey.ROONTRACKTAG to Id3FrameKey("TXXX", "ROONTRACKTAG"),
    FieldKey.SCRIPT to Id3FrameKey("TXXX", "SCRIPT"),
    FieldKey.SECTION to Id3FrameKey("TXXX", "SECTION"),
    FieldKey.SINGLE_DISC_TRACK_NO to Id3FrameKey("TXXX", "SINGLE_DISC_TRACK_NO"),
    FieldKey.SONGKONG_ID to Id3FrameKey("TXXX", "SONGKONG_ID"),
    FieldKey.SOUND_ENGINEER to Id3FrameKey("TXXX", "SOUND_ENGINEER"),
    FieldKey.SOUND_ENGINEER_SORT to Id3FrameKey("TXXX", "SOUND_ENGINEER_SORT"),
    FieldKey.SUBTITLE to Id3FrameKey("TIT3"),
    FieldKey.TAGS to Id3FrameKey("TXXX", "TAGS"),
    FieldKey.TEMPO to Id3FrameKey("COMM", "Songs-DB_Tempo"),
    FieldKey.TIMBRE to Id3FrameKey("TXXX", "TIMBRE_BRIGHTNESS"),
    FieldKey.TITLE to Id3FrameKey("TIT2"),
    FieldKey.TITLE_MOVEMENT to Id3FrameKey("TXXX", "TITLE_MOVEMENT"),
    FieldKey.TITLE_SORT to Id3FrameKey("TSOT"),
    FieldKey.TONALITY to Id3FrameKey("TXXX", "TONALITY"),
    FieldKey.TRACK to Id3FrameKey("TRCK"),
    FieldKey.TRACK_TOTAL to Id3FrameKey("TRCK"),
    FieldKey.URL_BANDCAMP_ARTIST_SITE to Id3FrameKey("WXXX", "BANDCAMP_ARTIST"),
    FieldKey.URL_BANDCAMP_RELEASE_SITE to Id3FrameKey("WXXX", "BANDCAMP_RELEASE"),
    FieldKey.URL_DISCOGS_ARTIST_SITE to Id3FrameKey("WXXX", "DISCOGS_ARTIST"),
    FieldKey.URL_DISCOGS_RELEASE_SITE to Id3FrameKey("WXXX", "DISCOGS_RELEASE"),
    FieldKey.URL_LYRICS_SITE to Id3FrameKey("WXXX", "LYRICS_SITE"),
    FieldKey.URL_OFFICIAL_ARTIST_SITE to Id3FrameKey("WOAR"),
    FieldKey.URL_OFFICIAL_RELEASE_SITE to Id3FrameKey("WXXX", "OFFICIAL_RELEASE"),
    FieldKey.URL_WIKIPEDIA_ARTIST_SITE to Id3FrameKey("WXXX", "WIKIPEDIA_ARTIST"),
    FieldKey.URL_WIKIPEDIA_RELEASE_SITE to Id3FrameKey("WXXX", "WIKIPEDIA_RELEASE"),
    FieldKey.WORK to Id3FrameKey("TXXX", "WORK"),
    FieldKey.MUSICBRAINZ_RECORDING_WORK to Id3FrameKey("TXXX", "MUSICBRAINZ_RECORDING_WORK"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL1"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL1_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL2"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL2_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL3"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL3_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL4"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL4_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL5"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL5_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6 to Id3FrameKey("TXXX", "MUSICBRAINZ_WORK_PART_LEVEL6"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_TYPE to Id3FrameKey(
        "TXXX",
        "MUSICBRAINZ_WORK_PART_LEVEL6_TYPE"
    ),
    FieldKey.VERSION to Id3FrameKey("TXXX", "VERSION"),
    FieldKey.WORK_TYPE to Id3FrameKey("TXXX", "WORK_TYPE"),
    FieldKey.YEAR to Id3FrameKey("TYER"),
    FieldKey.WORK to Id3FrameKey("TIT1"),
    FieldKey.GROUPING to Id3FrameKey("GRP1"),
    FieldKey.WORK to Id3FrameKey("TXXX", "WORK"),
    FieldKey.GROUPING to Id3FrameKey("TIT1"),
)

internal val id3v22FrameKeys: Map<FieldKey, Id3FrameKey> = mapOf(
    FieldKey.ACOUSTID_FINGERPRINT to Id3FrameKey("TXX", "Acoustid Fingerprint"),
    FieldKey.ACOUSTID_ID to Id3FrameKey("TXX", "Acoustid Id"),
    FieldKey.ALBUM to Id3FrameKey("TAL"),
    FieldKey.ALBUM_ARTIST to Id3FrameKey("TP2"),
    FieldKey.ALBUM_ARTIST_SORT to Id3FrameKey("TS2"),
    FieldKey.ALBUM_ARTISTS to Id3FrameKey("TXX", "ALBUM_ARTISTS"),
    FieldKey.ALBUM_ARTISTS_SORT to Id3FrameKey("TXX", "ALBUM_ARTISTS_SORT"),
    FieldKey.ALBUM_COMPOSER to Id3FrameKey("TXX", "ALBUM_COMPOSER"),
    FieldKey.ALBUM_COMPOSER_SORT to Id3FrameKey("TXX", "ALBUM_COMPOSER_SORT"),
    FieldKey.ALBUM_SORT to Id3FrameKey("TSA"),
    FieldKey.ALBUM_YEAR to Id3FrameKey("TXX", "ALBUM_YEAR"),
    FieldKey.AMAZON_ID to Id3FrameKey("TXX", "ASIN"),
    FieldKey.ARRANGER to Id3FrameKey("TXX", "ARRANGER"),
    FieldKey.ARRANGER_SORT to Id3FrameKey("TXX", "ARRANGER_SORT"),
    FieldKey.ARTIST to Id3FrameKey("TP1"),
    FieldKey.ARTISTS to Id3FrameKey("TXX", "ARTISTS"),
    FieldKey.ARTISTS_SORT to Id3FrameKey("TXX", "ARTISTS_SORT"),
    FieldKey.ARTIST_SORT to Id3FrameKey("TSP"),
    FieldKey.AUDIO_ENGINEER to Id3FrameKey("TXX", "AUDIO_ENGINEER"),
    FieldKey.AUDIO_ENGINEER_SORT to Id3FrameKey("TXX", "AUDIO_ENGINEER_SORT"),
    FieldKey.BALANCE_ENGINEER to Id3FrameKey("TXX", "BALANCE_ENGINEER"),
    FieldKey.BALANCE_ENGINEER_SORT to Id3FrameKey("TXX", "BALANCE_ENGINEER_SORT"),
    FieldKey.BARCODE to Id3FrameKey("TXX", "BARCODE"),
    FieldKey.BPM to Id3FrameKey("TBP"),
    FieldKey.CATALOG_NO to Id3FrameKey("TXX", "CATALOGNUMBER"),
    FieldKey.CHOIR to Id3FrameKey("TXX", "CHOIR"),
    FieldKey.CHOIR_SORT to Id3FrameKey("TXX", "CHOIR_SORT"),
    FieldKey.CLASSICAL_CATALOG to Id3FrameKey("TXX", "CLASSICAL_CATALOG"),
    FieldKey.CLASSICAL_NICKNAME to Id3FrameKey("TXX", "CLASSICAL_NICKNAME"),
    FieldKey.COMMENT to Id3FrameKey("COM"),
    FieldKey.COMPOSER to Id3FrameKey("TCM"),
    FieldKey.COMPOSER_SORT to Id3FrameKey("TSC"),
    FieldKey.CONDUCTOR to Id3FrameKey("TP3"),
    FieldKey.CONDUCTOR_SORT to Id3FrameKey("TXX", "CONDUCTOR_SORT"),
    FieldKey.COUNTRY to Id3FrameKey("TXX", "Country"),
    FieldKey.COPYRIGHT to Id3FrameKey("TCR"),
    FieldKey.COVER_ART to Id3FrameKey("PIC", isBinary = true),
    FieldKey.CREDITS to Id3FrameKey("TXX", "CREDITS"),
    FieldKey.CUSTOM1 to Id3FrameKey("COM", "Songs-DB_Custom1"),
    FieldKey.CUSTOM2 to Id3FrameKey("COM", "Songs-DB_Custom2"),
    FieldKey.CUSTOM3 to Id3FrameKey("COM", "Songs-DB_Custom3"),
    FieldKey.CUSTOM4 to Id3FrameKey("COM", "Songs-DB_Custom4"),
    FieldKey.CUSTOM5 to Id3FrameKey("COM", "Songs-DB_Custom5"),
    FieldKey.DISC_NO to Id3FrameKey("TPA"),
    FieldKey.DISC_SUBTITLE to Id3FrameKey("TPS"),
    FieldKey.DISC_TOTAL to Id3FrameKey("TPA"),
    FieldKey.DJMIXER to Id3FrameKey("TXX", "DJMIXER"),
    FieldKey.DJMIXER_SORT to Id3FrameKey("TXX", "DJMIXER_SORT"),
    FieldKey.ENCODER to Id3FrameKey("TEN"),
    FieldKey.ENGINEER to Id3FrameKey("TXX", "ENGINEER"),
    FieldKey.ENGINEER_SORT to Id3FrameKey("TXX", "ENGINEER_SORT"),
    FieldKey.ENSEMBLE to Id3FrameKey("TXX", "ENSEMBLE"),
    FieldKey.ENSEMBLE_SORT to Id3FrameKey("TXX", "ENSEMBLE_SORT"),
    FieldKey.FBPM to Id3FrameKey("TXX", "FBPM"),
    FieldKey.GENRE to Id3FrameKey("TCO"),
    FieldKey.GROUP to Id3FrameKey("TXX", "GROUP"),
    FieldKey.GROUPING to Id3FrameKey("TT1"),
    FieldKey.INSTRUMENT to Id3FrameKey("TXX", "INSTRUMENT"),
    FieldKey.INVOLVEDPEOPLE to Id3FrameKey("IPL"),
    FieldKey.IPI to Id3FrameKey("TXX", "IPI"),
    FieldKey.ISRC to Id3FrameKey("TRC"),
    FieldKey.ISWC to Id3FrameKey("TXX", "ISWC"),
    FieldKey.IS_CLASSICAL to Id3FrameKey("TXX", "IS_CLASSICAL"),
    FieldKey.IS_COMPILATION to Id3FrameKey("TCP"),
    FieldKey.IS_GREATEST_HITS to Id3FrameKey("TXX", "IS_GREATEST_HITS"),
    FieldKey.IS_HD to Id3FrameKey("TXX", "IS_HD"),
    FieldKey.IS_LIVE to Id3FrameKey("TXX", "LIVE"),
    FieldKey.IS_SOUNDTRACK to Id3FrameKey("TXX", "IS_SOUNDTRACK"),
    FieldKey.ITUNES_GROUPING to Id3FrameKey("GP1"),
    FieldKey.JAIKOZ_ID to Id3FrameKey("TXX", "JAIKOZ_ID"),
    FieldKey.KEY to Id3FrameKey("TKE"),
    FieldKey.LANGUAGE to Id3FrameKey("TLA"),
    FieldKey.LYRICIST to Id3FrameKey("TXT"),
    FieldKey.LYRICIST_SORT to Id3FrameKey("TXX", "LYRICIST_SORT"),
    FieldKey.LYRICS to Id3FrameKey("ULT"),
    FieldKey.MASTERING to Id3FrameKey("TXX", "MASTERING"),
    FieldKey.MASTERING_SORT to Id3FrameKey("TXX", "MASTERING_SORT"),
    FieldKey.MEDIA to Id3FrameKey("TMT"),
    FieldKey.MIXER to Id3FrameKey("TXX", "MIXER"),
    FieldKey.MIXER_SORT to Id3FrameKey("TXX", "MIXER_SORT"),
    FieldKey.MOOD to Id3FrameKey("TXX", "MOOD"),
    FieldKey.MOOD_ACOUSTIC to Id3FrameKey("TXX", "MOOD_ACOUSTIC"),
    FieldKey.MOOD_AGGRESSIVE to Id3FrameKey("TXX", "MOOD_AGGRESSIVE"),
    FieldKey.MOOD_AROUSAL to Id3FrameKey("TXX", "MOOD_AROUSAL"),
    FieldKey.MOOD_DANCEABILITY to Id3FrameKey("TXX", "MOOD_DANCEABILITY"),
    FieldKey.MOOD_ELECTRONIC to Id3FrameKey("TXX", "MOOD_ELECTRONIC"),
    FieldKey.MOOD_HAPPY to Id3FrameKey("TXX", "MOOD_HAPPY"),
    FieldKey.MOOD_INSTRUMENTAL to Id3FrameKey("TXX", "MOOD_INSTRUMENTAL"),
    FieldKey.MOOD_PARTY to Id3FrameKey("TXX", "MOOD_PARTY"),
    FieldKey.MOOD_RELAXED to Id3FrameKey("TXX", "MOOD_RELAXED"),
    FieldKey.MOOD_SAD to Id3FrameKey("TXX", "MOOD_SAD"),
    FieldKey.MOOD_VALENCE to Id3FrameKey("TXX", "MOOD_VALENCE"),
    FieldKey.MOVEMENT to Id3FrameKey("MVN"),
    FieldKey.MOVEMENT_NO to Id3FrameKey("MVI"),
    FieldKey.MOVEMENT_TOTAL to Id3FrameKey("MVI"),
    FieldKey.MUSICBRAINZ_ARTISTID to Id3FrameKey("TXX", "MusicBrainz Artist Id"),
    FieldKey.MUSICBRAINZ_DISC_ID to Id3FrameKey("TXX", "MusicBrainz Disc Id"),
    FieldKey.MUSICBRAINZ_ORIGINAL_RELEASE_ID to Id3FrameKey("TXX", "MusicBrainz Original Album Id"),
    FieldKey.MUSICBRAINZ_RELEASEARTISTID to Id3FrameKey("TXX", "MusicBrainz Album Artist Id"),
    FieldKey.MUSICBRAINZ_RELEASEID to Id3FrameKey("TXX", "MusicBrainz Album Id"),
    FieldKey.MUSICBRAINZ_RELEASE_COUNTRY to Id3FrameKey("TXX", "MusicBrainz Album Release Country"),
    FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID to Id3FrameKey("TXX", "MusicBrainz Release Group Id"),
    FieldKey.MUSICBRAINZ_RELEASE_STATUS to Id3FrameKey("TXX", "MusicBrainz Album Status"),
    FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID to Id3FrameKey("TXX", "MusicBrainz Release Track Id"),
    FieldKey.MUSICBRAINZ_RELEASE_TYPE to Id3FrameKey("TXX", "MusicBrainz Album Type"),
    FieldKey.MUSICBRAINZ_TRACK_ID to Id3FrameKey("UFI", "http://musicbrainz.org"),
    FieldKey.MUSICBRAINZ_WORK to Id3FrameKey("TXX", "MUSICBRAINZ_WORK"),
    FieldKey.MUSICBRAINZ_WORK_ID to Id3FrameKey("TXX", "MusicBrainz Work Id"),
    FieldKey.MUSICBRAINZ_RECORDING_WORK_ID to Id3FrameKey("TXX", "MUSICBRAINZ_RECORDING_WORK_ID"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL1_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL2_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL3_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL4_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL5_ID"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL6_ID"
    ),
    FieldKey.MUSICIP_ID to Id3FrameKey("TXX", "MusicIP PUID"),
    FieldKey.OCCASION to Id3FrameKey("COM", "Songs-DB_Occasion"),
    FieldKey.OPUS to Id3FrameKey("TXX", "OPUS"),
    FieldKey.ORCHESTRA to Id3FrameKey("TXX", "ORCHESTRA"),
    FieldKey.ORCHESTRA_SORT to Id3FrameKey("TXX", "ORCHESTRA_SORT"),
    FieldKey.ORIGINAL_ALBUM to Id3FrameKey("TOT"),
    FieldKey.ORIGINALRELEASEDATE to Id3FrameKey("TXX", "ORIGINALRELEASEDATE"),
    FieldKey.ORIGINAL_ARTIST to Id3FrameKey("TOA"),
    FieldKey.ORIGINAL_LYRICIST to Id3FrameKey("TOL"),
    FieldKey.ORIGINAL_YEAR to Id3FrameKey("TOR"),
    FieldKey.OVERALL_WORK to Id3FrameKey("TXX", "OVERALL_WORK"),
    FieldKey.PART to Id3FrameKey("TXX", "PART"),
    FieldKey.PART_NUMBER to Id3FrameKey("TXX", "PARTNUMBER"),
    FieldKey.PART_TYPE to Id3FrameKey("TXX", "PART_TYPE"),
    FieldKey.PERFORMER to Id3FrameKey("TXX", "PERFORMER"),
    FieldKey.PERFORMER_NAME to Id3FrameKey("TXX", "PERFORMER_NAME"),
    FieldKey.PERFORMER_NAME_SORT to Id3FrameKey("TXX", "PERFORMER_NAME_SORT"),
    FieldKey.PERIOD to Id3FrameKey("TXX", "PERIOD"),
    FieldKey.PRODUCER to Id3FrameKey("TXX", "PRODUCER"),
    FieldKey.PRODUCER_SORT to Id3FrameKey("TXX", "PRODUCER_SORT"),
    FieldKey.QUALITY to Id3FrameKey("COM", "Songs-DB_Preference"),
    FieldKey.RANKING to Id3FrameKey("TXX", "RANKING"),
    FieldKey.RATING to Id3FrameKey("POP"),
    FieldKey.RECORDING_ENGINEER to Id3FrameKey("TXX", "RECORDING_ENGINEER"),
    FieldKey.RECORDING_ENGINEER_SORT to Id3FrameKey("TXX", "RECORDING_ENGINEER_SORT"),
    FieldKey.RECORD_LABEL to Id3FrameKey("TPB"),
    FieldKey.RECORDINGDATE to Id3FrameKey("TXX", "RECORDINGDATE"),
    FieldKey.RECORDINGSTARTDATE to Id3FrameKey("TXX", "RECORDINGSTARTDATE"),
    FieldKey.RECORDINGENDDATE to Id3FrameKey("TXX", "RECORDINGENDDATE"),
    FieldKey.RECORDINGLOCATION to Id3FrameKey("TXX", "RECORDINGLOCATION"),
    FieldKey.REMIXER to Id3FrameKey("TP4"),
    FieldKey.ROONALBUMTAG to Id3FrameKey("TXX", "ROONALBUMTAG"),
    FieldKey.ROONTRACKTAG to Id3FrameKey("TXX", "ROONTRACKTAG"),
    FieldKey.SCRIPT to Id3FrameKey("TXX", "SCRIPT"),
    FieldKey.SECTION to Id3FrameKey("TXX", "SECTION"),
    FieldKey.SINGLE_DISC_TRACK_NO to Id3FrameKey("TXX", "SINGLE_DISC_TRACK_NO"),
    FieldKey.SONGKONG_ID to Id3FrameKey("TXX", "SONGKONG_ID"),
    FieldKey.SOUND_ENGINEER to Id3FrameKey("TXX", "SOUND_ENGINEER"),
    FieldKey.SOUND_ENGINEER_SORT to Id3FrameKey("TXX", "SOUND_ENGINEER_SORT"),
    FieldKey.SUBTITLE to Id3FrameKey("TT3"),
    FieldKey.TAGS to Id3FrameKey("TXX", "TAGS"),
    FieldKey.TEMPO to Id3FrameKey("COM", "Songs-DB_Tempo"),
    FieldKey.TIMBRE to Id3FrameKey("TXX", "TIMBRE_BRIGHTNESS"),
    FieldKey.TITLE to Id3FrameKey("TT2"),
    FieldKey.TITLE_MOVEMENT to Id3FrameKey("TXX", "TITLE_MOVEMENT"),
    FieldKey.TITLE_SORT to Id3FrameKey("TST"),
    FieldKey.TONALITY to Id3FrameKey("TXX", "TONALITY"),
    FieldKey.TRACK to Id3FrameKey("TRK"),
    FieldKey.TRACK_TOTAL to Id3FrameKey("TRK"),
    FieldKey.URL_BANDCAMP_ARTIST_SITE to Id3FrameKey("WXX", "BANDCAMP_ARTIST"),
    FieldKey.URL_BANDCAMP_RELEASE_SITE to Id3FrameKey("WXX", "BANDCAMP_RELEASE"),
    FieldKey.URL_DISCOGS_ARTIST_SITE to Id3FrameKey("WXX", "DISCOGS_ARTIST"),
    FieldKey.URL_DISCOGS_RELEASE_SITE to Id3FrameKey("WXX", "DISCOGS_RELEASE"),
    FieldKey.URL_LYRICS_SITE to Id3FrameKey("WXX", "LYRICS_SITE"),
    FieldKey.URL_OFFICIAL_ARTIST_SITE to Id3FrameKey("WAR"),
    FieldKey.URL_OFFICIAL_RELEASE_SITE to Id3FrameKey("WXX", "OFFICIAL_RELEASE"),
    FieldKey.URL_WIKIPEDIA_ARTIST_SITE to Id3FrameKey("WXX", "WIKIPEDIA_ARTIST"),
    FieldKey.URL_WIKIPEDIA_RELEASE_SITE to Id3FrameKey("WXX", "WIKIPEDIA_RELEASE"),
    FieldKey.VERSION to Id3FrameKey("TXX", "VERSION"),
    FieldKey.WORK to Id3FrameKey("TXX", "WORK"),
    FieldKey.MUSICBRAINZ_RECORDING_WORK to Id3FrameKey("TXX", "MUSICBRAINZ_RECORDING_WORK"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1 to Id3FrameKey("TXX", "MUSICBRAINZ_WORK_PART_LEVEL1"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_TYPE to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL1_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2 to Id3FrameKey("TXX", "MUSICBRAINZ_WORK_PART_LEVEL2"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_TYPE to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL2_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3 to Id3FrameKey("TXX", "MUSICBRAINZ_WORK_PART_LEVEL3"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_TYPE to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL3_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4 to Id3FrameKey("TXX", "MUSICBRAINZ_WORK_PART_LEVEL4"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_TYPE to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL4_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5 to Id3FrameKey("TXX", "MUSICBRAINZ_WORK_PART_LEVEL5"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_TYPE to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL5_TYPE"
    ),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6 to Id3FrameKey("TXX", "MUSICBRAINZ_WORK_PART_LEVEL6"),
    FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_TYPE to Id3FrameKey(
        "TXX",
        "MUSICBRAINZ_WORK_PART_LEVEL6_TYPE"
    ),
    FieldKey.WORK_TYPE to Id3FrameKey("TXX", "WORK_TYPE"),
    FieldKey.YEAR to Id3FrameKey("TYE"),
    FieldKey.WORK to Id3FrameKey("TT1"),
    FieldKey.GROUPING to Id3FrameKey("GP1"),
    FieldKey.WORK to Id3FrameKey("TXX", "WORK"),
    FieldKey.GROUPING to Id3FrameKey("TT1"),
)
